[package]
name = "mobile"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
dioxus = { workspace = true, features = [{{- router_feature -}}] }
ui = { workspace = true }

[features]
default = [{% if is_fullstack == false -%}"mobile"{%- endif %}]
mobile = ["dioxus/mobile"]
{% if is_fullstack -%}
server = ["dioxus/server"]
{%- endif %}
