[package]
name = "web"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
dioxus = { workspace = true, features = [{{- router_feature -}}] }
ui = { workspace = true }

[features]
default = [{% if is_fullstack == false -%}"web"{%- endif %}]
web = ["dioxus/web"]
{% if is_fullstack -%}
server = ["dioxus/server"]
{%- endif %}
