[workspace]
resolver = "3"
members = [
    "ui",
    {%- for member in workspace_members %}
    "{{- member -}}",
    {%- endfor %}
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
dioxus = { {{ dioxus_dep_src }} }

# workspace
ui = { path = "ui" }
{% if is_fullstack -%}
server = { path = "server" }
{%- endif %}
